<h1>Creating a logistic regression to predict absenteeism</h1>
<h2>Import the relevant libraries</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

<h2>Create the targets</h2>

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

<h2>A comment on the targets</h2>

In [8]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Date', 'Day of the week', 'Daily Work Load Average', 'Distance to Work'],axis=1)

In [10]:
data_with_targets is data_preprocessed

False

In [11]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0         0         0         0         1                     289   33   
1         0         0         0         0                     118   50   
2         0         0         0         1                     179   38   
3         1         0         0         0                     279   39   
4         0         0         0         1                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  \
0               30          0         2     1            7   
1               31          0         1     0            7   
2               31          0         0     0            7   
3               24          0         2     0            7   
4               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

<h2>Select the inputs for the regression</h2>

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

<h2>Standardize the data</h2>

In [15]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [18]:
# columns_to_scale = ['Month Value','Day of the week','Transportation Expense','Distance to Work','Age','Daily Work Load Average','Body Mass Index','Children','Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [21]:
absenteeism_scaler.fit(unscaled_inputs)

/home/paulo/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'],
             copy=None, with_mean=None, with_std=None)

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month Value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [24]:
scaled_inputs.shape

(700, 11)

<h2>Split the data into train & test and shuffle</h2>

<h2>Import the relevant module</h2>

In [25]:
from sklearn.model_selection import train_test_split

<h2>Split</h2>

In [26]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 331         1         0         0         0                1.036026  0.562059   
 375         0         0         0         1               -0.654143  0.248310   
 110         0         0         0         1               -1.574681  0.091435   
 677         1         0         0         0               -1.574681  0.091435   
 575         0         0         0         1               -0.654143  0.562059   
 ..        ...       ...       ...       ...                     ...       ...   
 486         0         0         0         1                1.036026  0.562059   
 95          0         0         0         1                0.040034 -1.320435   
 592         0         0         0         1                0.040034  0.718933   
 66          0         0         0         1               -0.654143  0.248310   
 123         0         0         0         1               -1.574681  0.091435   
 
      Body Mas

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [28]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [29]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


<h2>Logistic regression with sklearn</h2>

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

<h2>Training the model</h2>

In [31]:
reg = LogisticRegression()

In [32]:
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
reg.score(x_train, y_train)

0.7732142857142857

<h2>Manually check the accuracy</h2>

In [34]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [36]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [37]:
np.sum((model_outputs==y_train))

433

In [38]:
model_outputs.shape[0]

560

In [39]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7732142857142857

<h2>Finding the intercept and coefficients</h2>

In [40]:
reg.intercept_

array([-1.6474549])

In [41]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.60528415,
        -0.16989096,  0.27981088, -0.21053312,  0.34826214, -0.27739602,
         0.1589299 ]])

In [42]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [43]:
feature_name = unscaled_inputs.columns.values

In [44]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4   Transportation Expense     0.605284
5                      Age    -0.169891
6          Body Mass Index     0.279811
7                Education    -0.210533
8                 Children     0.348262
9                     Pets    -0.277396
10             Month Value     0.158930

In [45]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month Value     0.158930

<h2>Interpreting the coefficients</h2>

In [46]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [47]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
6                      Age    -0.169891    0.843757
7          Body Mass Index     0.279811    1.322880
8                Education    -0.210533    0.810152
9                 Children     0.348262    1.416604
10                    Pets    -0.277396    0.757754
11             Month Value     0.158930    1.172256

In [48]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
9                 Children     0.348262    1.416604
7          Body Mass Index     0.279811    1.322880
11             Month Value     0.158930    1.172256
6                      Age    -0.169891    0.843757
8                Education    -0.210533    0.810152
10                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

<h2>Testing the model</h2>

In [49]:
reg.score(x_test, y_test)

0.75

In [50]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [51]:
predicted_proba.shape

(140, 2)

In [52]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

<h2>Save the model</h2>

In [53]:
import pickle

In [54]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [56]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)