In [252]:
import pandas as pd
import numpy as np

In [315]:
header_names = [
    "ID_CLIENTE",
    "TIPO_FUNCIONARIO",
    "DIA_PAGAMENTO",
    "TIPO_ENVIO_APLICACAO",
    "QUANT_CARTOES_ADICIONAIS",
    "TIPO_ENDERECO_POSTAL",
    "SEXO",
    "ESTADO_CIVIL",
    "QUANT_DEPENDENTE",
    "NIVEL_EDUCACIONAL",
    "ESTADO_NASCIMENT",
    "CIDADE_NASCIMENT",
    "NACIONALIDADE",
    "ESTADO_RESIDENCIAL",
    "CIDADE_RESIDENCIAL",
    "BAIRRO_RESIDENCIAL",
    "FLAG_TELEFONE_RESIDENCIAL",
    "CODIGO_AREA_TELEFONE_RESIDENCIAL",
    "TIPO_RESIDENCIA",
    "MESES_RESIDENCIA",
    "FLAG_TELEFONE_MOVEL",
    "FLAG_EMAIL",
    "RENDA_PESSOAL_MENSAL",
    "OUTRAS_RENDAS",
    "FLAG_VISA",
    "FLAG_MASTERCARD",
    "FLAG_DINERS",
    "FLAG_AMERICAN_EXPRESS",
    "FLAG_OUTROS_CARTOES",
    "QUANT_CONTAS_BANCARIAS",
    "QUANT_CONTAS_BANCARIAS_ESPECIAIS",
    "VALOR_PATRIMONIO_PESSOAL",
    "QUANT_CARROS",
    "EMPRESA",
    "ESTADO_PROFISSIONAL",
    "IDADE_PROFISSIONAL",
    "BAIRRO_PROFISSIONAL",
    "FLAG_TELEFONE_PROFISSIONAL",
    "ODIGO_AREA_TELEFONE_PROFISSIONAL",
    "MESES_NO_TRABALHO",
    "CODIGO_PROFISSAO",
    "TIPO_OCUPACAO",
    "CODIGO_PROFISSAO_CONJUGE",
    "NIVEL_EDUCACIONAL_CONJUGE",
    "FLAG_DOCUMENTO_RESIDENCIAL",
    "FLAG_RG",
    "FLAG_CPF",
    "FLAG_COMPROVANTE_RENDA",
    "PRODUTO",
    "FLAG_REGISTRO_ACSP",
    "IDADE",
    "CEP_RESIDENCIAL_3",
    "CEP_PROFISSIONAL_3",
    "ROTULO_ALVO_MAU=1",
]

df = pd.read_csv("clean_credit.csv", encoding='unicode_escape', sep='\t', engine='python', names=header_names)

In [349]:
data = np.genfromtxt('credit.csv',delimiter='\t',usecols=np.arange(0,52))

In [351]:
data.shape

(50000, 52)

In [355]:
data.view()

array([[    1.,    nan,     5., ...,    nan,    32.,   595.],
       [    2.,    nan,    15., ...,    nan,    34.,   230.],
       [    3.,    nan,     5., ...,    nan,    27.,   591.],
       ...,
       [49998.,    nan,     5., ...,    nan,    41.,   715.],
       [49999.,    nan,     1., ...,    nan,    28.,   320.],
       [50000.,    nan,    10., ...,    nan,    27.,   124.]])

In [359]:
np.isnan(data).sum()

906691

In [363]:
valores_nan = np.nanmax(data) + 3
print(valores_nan)

30011977.0


In [369]:
media_sem_nan = np.nanmean(data, axis = 0)
print(media_sem_nan)

[   25000.5              nan       12.8699        0.            0.            1.0065           nan        2.1484        0.6505        0.               nan 17156967.6           0.9616           nan
           nan           nan           nan       64.5442        1.2522        9.7271           nan        0.8023      886.6784       35.4348        0.1114        0.0975        0.0013        0.0017
        0.002         0.3578        0.3578     2322.3724        0.3361           nan           nan           nan           nan           nan       62.397         0.0093        8.0618        2.4843
        3.7979        0.296         0.            0.            0.            0.            1.2757           nan       43.2485      585.1658]


/var/folders/4k/q5xn50lx7hb2slknt2ygk7hc0000gn/T/ipykernel_2390/352713117.py:1: RuntimeWarning: Mean of empty slice
  media_sem_nan = np.nanmean(data, axis = 0)


In [371]:
cols_str = np.argwhere(np.isnan(media_sem_nan)).squeeze() 
cols_str

array([ 1,  6, 10, 13, 14, 15, 16, 20, 33, 34, 35, 36, 37, 49])

In [373]:
cols_num = np.argwhere(np.isnan(media_sem_nan) == False).squeeze()
cols_num

array([ 0,  2,  3,  4,  5,  7,  8,  9, 11, 12, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51])

In [377]:
str_data = np.genfromtxt("credit.csv",
                            delimiter = '\t', 
                            usecols = cols_str,
                            dtype = str)

In [381]:
str_data

array([['C', 'F', 'RN', ..., 'NULL', 'N', 'N'],
       ['C', 'F', 'RJ', ..., 'NULL', 'N', 'N'],
       ['C', 'F', 'RN', ..., 'NULL', 'N', 'N'],
       ...,
       ['C', 'M', 'PR', ..., 'ITAPEGICA', 'Y', 'N'],
       ['C', 'F', 'SP', ..., 'JARDIM ALTEROSA', 'Y', 'N'],
       ['C', 'F', 'SP', ..., 'CIDADE NOVA', 'Y', 'N']], dtype='<U40')

In [383]:
num_data = np.genfromtxt("credit.csv",
                            delimiter = '\t',
                            usecols = cols_num,
                            filling_values = valores_nan)

In [385]:
num_data

array([[       1.,        5., 30011977., ...,        1.,       32.,      595.],
       [       2.,       15., 30011977., ...,        1.,       34.,      230.],
       [       3.,        5., 30011977., ...,        1.,       27.,      591.],
       ...,
       [   49998.,        5., 30011977., ...,        1.,       41.,      715.],
       [   49999.,        1., 30011977., ...,        1.,       28.,      320.],
       [   50000.,       10., 30011977., ...,        1.,       27.,      124.]])